kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kbench-pvc
spec:
  volumeMode: Filesystem
  #volumeMode: Block
  #storageClassName: longhorn  # replace with your storage class
  #storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 33Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kbench
spec:
  template:
    metadata:
      labels:
        kbench: fio
    spec:
      containers:
      - name: kbench
        image: yasker/kbench:latest
        imagePullPolicy: Always
        env:
#        - name: MODE
#          value: "quick" # for debugging
#        - name: MODE
#          value: "random-read-iops"
#        - name: MODE
#          value: "sequential-read-iops"
#        - name: MODE
#          value: "random-read-bandwidth"
#        - name: MODE
#          value: "sequential-read-bandwidth"
#        - name: MODE
#          value: "random-read-latency"
#        - name: MODE
#          value: "sequential-read-latency"
#        - name: MODE
#          value: "random-write-iops"
#        - name: MODE
#          value: "sequential-write-iops"
#        - name: MODE
#          value: "random-write-bandwidth"
#        - name: MODE
#          value: "sequential-write-bandwidth"
#        - name: MODE
#          value: "random-write-latency"
#        - name: MODE
#          value: "sequential-write-latency"
        - name: MODE
          value: "full" # run all tests
        - name: FILE_NAME
          value: "/volume/test"
        - name: SIZE
          value: "30G" # must be 10% smaller than the PVC size due to filesystem also took space
        - name: CPU_IDLE_PROF
          value: "disabled" # must be "enabled" or "disabled"
        volumeMounts:
        - name: vol
          mountPath: /volume/
        #volumeDevices:
        #- name: vol
        #  devicePath: /volume/test
      restartPolicy: Never
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: kbench-pvc
  backoffLimit: 0
